Student home
GtechDevelopers070/DecLine pull request #1
Opened 2018-03-16 06:32 UTC by Ishanliv99

*Complete basic Student Home Page with Modals
*Added feature to add modals

Run 'yarn' after pulling

2018-03-16 16:14 UTC, abiralacharya reviewed
use branch name in all lower case

2018-03-16 16:14 UTC, abiralacharya commented on App.test.js
> +import App from './App';
separate it with a line

2018-03-17 04:12 UTC, yushghimire reviewed
1. Cannot go back after in add class modal
2. Classes are not center aligned 
3. Empty submit is allowed in classes added

2018-03-17 10:57 UTC, abiralacharya approved these changes

2018-03-17 11:01 UTC, abiralacharya submitted a review, later dismissed
Nice!!

2018-03-17 11:06 UTC, yushghimire requested changes
implement ladder

2018-03-17 11:06 UTC, yushghimire commented on src/Index.js
> +      allClasses: ['CS 101', 'ECON 303', 'HIST 201'],
implement ladder in state

2018-03-17 11:11 UTC, yushghimire approved these changes

2018-03-17 11:13 UTC, abiralacharya approved these changes

2018-03-17 11:13 UTC, merged